version: '3'
services:
  web:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./env/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: always
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    env_file:
      - ./env/grafana.env
    volumes:
      - ./env/provisioning/:/etc/grafana/provisioning/
#      - ./env/grafana.ini:/etc/grafana/grafana.ini
    restart: always

